name: beLazy
favicon: null
layout_spectrum: 0
typography_spectrum: 0.22376
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1f1f'
    - '#d2d2d2'
    - '#010101'
    - '#8b8b8b'
    - '#616161'
  brandStrength: 0
  lightness: 0.7326015974394977
  saturation: 0
  rhythmicContrast: 0.2724353172816336
purpose: []
