name: beLazy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2926236030180007
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#121211'
    - '#a0bed1'
    - '#4e4c51'
    - '#9b774e'
  brandStrength: 0.1861574810463935
  lightness: 0.7326015974394977
  saturation: 0.6638886234723032
  rhythmicContrast: 0.2724353172816336
purpose: []
